server:
  application:
    name: server
  port: 8082

spring:
  security:
    filter:
      chain:
        authorization:
          rules:
            - pattern: /api/**
              access: hasAuthority('SCOPE_read:data')
            - pattern: /**
              access: denyAll
            
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/demorealm
