spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: <Add>
            client-secret: <Add>
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            issuer-uri: https://accounts.google.com
